"""autogenerated by genpy from Echoes/BlinkingLedRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BlinkingLedRequest(genpy.Message):
  _md5sum = "53095c198b4a7b723a7d4c97845aef2f"
  _type = "Echoes/BlinkingLedRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool on
bool blinks


"""
  __slots__ = ['on','blinks']
  _slot_types = ['bool','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       on,blinks

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BlinkingLedRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.on is None:
        self.on = False
      if self.blinks is None:
        self.blinks = False
    else:
      self.on = False
      self.blinks = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.on, _x.blinks))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.on, _x.blinks,) = _struct_2B.unpack(str[start:end])
      self.on = bool(self.on)
      self.blinks = bool(self.blinks)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_2B.pack(_x.on, _x.blinks))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 2
      (_x.on, _x.blinks,) = _struct_2B.unpack(str[start:end])
      self.on = bool(self.on)
      self.blinks = bool(self.blinks)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_2B = struct.Struct("<2B")
"""autogenerated by genpy from Echoes/BlinkingLedResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BlinkingLedResponse(genpy.Message):
  _md5sum = "6b6d4c3b5d9d236dae096b76debe50d5"
  _type = "Echoes/BlinkingLedResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """bool requestSuccessful

"""
  __slots__ = ['requestSuccessful']
  _slot_types = ['bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       requestSuccessful

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BlinkingLedResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.requestSuccessful is None:
        self.requestSuccessful = False
    else:
      self.requestSuccessful = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_B.pack(self.requestSuccessful))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 1
      (self.requestSuccessful,) = _struct_B.unpack(str[start:end])
      self.requestSuccessful = bool(self.requestSuccessful)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_B.pack(self.requestSuccessful))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 1
      (self.requestSuccessful,) = _struct_B.unpack(str[start:end])
      self.requestSuccessful = bool(self.requestSuccessful)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B = struct.Struct("<B")
class BlinkingLed(object):
  _type          = 'Echoes/BlinkingLed'
  _md5sum = '3fbdacaab452e57ecfde1d88f4f7b065'
  _request_class  = BlinkingLedRequest
  _response_class = BlinkingLedResponse
