(cl:defpackage Echoes-srv
  (:use )
  (:export
   "RESETLED"
   "<RESETLED-REQUEST>"
   "RESETLED-REQUEST"
   "<RESETLED-RESPONSE>"
   "RESETLED-RESPONSE"
   "BLINKINGLED"
   "<BLINKINGLED-REQUEST>"
   "BLINKINGLED-REQUEST"
   "<BLINKINGLED-RESPONSE>"
   "BLINKINGLED-RESPONSE"
   "FIXEDLED"
   "<FIXEDLED-REQUEST>"
   "FIXEDLED-REQUEST"
   "<FIXEDLED-RESPONSE>"
   "FIXEDLED-RESPONSE"
  ))

