/* Auto-generated by genmsg_cpp for file /home/mikel/workspace/ros/PacBot/PacBot/Echoes/msg/Rfid.msg */
#ifndef ECHOES_MESSAGE_RFID_H
#define ECHOES_MESSAGE_RFID_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace Echoes
{
template <class ContainerAllocator>
struct Rfid_ {
  typedef Rfid_<ContainerAllocator> Type;

  Rfid_()
  : id()
  {
  }

  Rfid_(const ContainerAllocator& _alloc)
  : id(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _id_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  id;


  typedef boost::shared_ptr< ::Echoes::Rfid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Echoes::Rfid_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Rfid
typedef  ::Echoes::Rfid_<std::allocator<void> > Rfid;

typedef boost::shared_ptr< ::Echoes::Rfid> RfidPtr;
typedef boost::shared_ptr< ::Echoes::Rfid const> RfidConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::Echoes::Rfid_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::Echoes::Rfid_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace Echoes

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::Echoes::Rfid_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::Echoes::Rfid_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::Echoes::Rfid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bbfcda76036ebbe3d36caf7af80b260c";
  }

  static const char* value(const  ::Echoes::Rfid_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xbbfcda76036ebbe3ULL;
  static const uint64_t static_value2 = 0xd36caf7af80b260cULL;
};

template<class ContainerAllocator>
struct DataType< ::Echoes::Rfid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Echoes/Rfid";
  }

  static const char* value(const  ::Echoes::Rfid_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::Echoes::Rfid_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string id\n\
\n\
";
  }

  static const char* value(const  ::Echoes::Rfid_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::Echoes::Rfid_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Rfid_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Echoes::Rfid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::Echoes::Rfid_<ContainerAllocator> & v) 
  {
    s << indent << "id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.id);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ECHOES_MESSAGE_RFID_H

